/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
    "./about_us/index.html",
    "./landing_guest/index.html",
    "./landing_logged_in/index.html",
    "./login/index.html",
    "./property_details_primary/index.html",
    "./property_details_secondary/index.html",
    "./secure_access/index.html",
    "./Rgister_user/index.html",
  ],
  theme: {
    extend: {
      colors: {
        "on-tertiary-container": "#fff0e7",
        "surface-container-high": "#282a2a",
        "tertiary-fixed": "#ffdcc3",
        "primary-fixed": "#a0efff",
        "surface-dim": "#121414",
        "inverse-primary": "#006876",
        background: "#121414",
        "surface-container": "#1e2020",
        "on-background": "#e2e2e2",
        "surface-bright": "#383939",
        error: "#ffb4ab",
        "outline-variant": "#3e494b",
        "on-tertiary-fixed": "#2f1500",
        "surface-container-lowest": "#0d0f0f",
        "on-secondary": "#14353b",
        "inverse-on-surface": "#2f3131",
        "on-tertiary-fixed-variant": "#6e3900",
        "surface-container-low": "#1a1c1c",
        tertiary: "#ffb77c",
        "primary-container": "#007a8a",
        secondary: "#abccd4",
        "surface-tint": "#7ad4e5",
        "on-tertiary": "#4d2600",
        "on-surface": "#e2e2e2",
        "secondary-fixed-dim": "#abccd4",
        "secondary-container": "#2c4b52",
        "on-secondary-fixed": "#001f25",
        "on-error": "#690005",
        "on-primary-fixed": "#001f25",
        "secondary-fixed": "#c7e8f0",
        "primary-fixed-dim": "#7ad4e5",
        "surface-container-highest": "#333535",
        "on-secondary-container": "#9abbc2",
        surface: "#121414",
        "error-container": "#93000a",
        "tertiary-container": "#9e6027",
        "inverse-surface": "#e2e2e2",
        "on-primary-container": "#daf8ff",
        primary: "#7ad4e5",
        outline: "#889395",
        "on-error-container": "#ffdad6",
        "tertiary-fixed-dim": "#ffb77c",
        "on-surface-variant": "#bdc8cb",
        "on-primary-fixed-variant": "#004e59",
        "on-primary": "#00363e",
        "surface-variant": "#333535",
        "on-secondary-fixed-variant": "#2c4b52",
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px",
      },
      fontFamily: {
        headline: ["Manrope", "system-ui", "sans-serif"],
        body: ["Inter", "system-ui", "sans-serif"],
        label: ["Inter", "system-ui", "sans-serif"],
      },
      boxShadow: {
        "ambient-lg": "0 40px 80px rgba(13, 15, 15, 0.35)",
      },
    },
  },
  plugins: [require("@tailwindcss/forms"), require("@tailwindcss/container-queries")],
}

